---
title: "Assignment for Class 1"
---

### Misc. Links

We didn't get to this notes, so you'll need to read them on your own. Come prepared next class with questions, comments, etc. 

- [[notes](files/01b-notes-questions.html) on questions]
- [[notes](files/01c-notes-models.html) on models] 


We didn't use the slides below. There's no need for you to review them---everything is in the notes.

- [[slides](files/01b-slides-questions.pdf) on questions] 
- [[slides](files/01c-slides-models.pdf) on models] 

In class, we used [Gapminder](https://www.gapminder.org/tools/#$chart-type=bubbles&url=v2) to explore some data.



### Homework

Please complete before the next class.

- Read the [syllabus](syllabus.pdf) carefully. If I've missed anything or failed to clearly explain any policy, please let me know. Come prepared to the next class with any questions or comments.
- Order the [simple pocket calculator](https://www.amazon.com/gp/aw/d/B003822IRA/) that you'll need for homework and exams, or make a plan to buy one (e.g., Walmart or other stores). Any "pocket" calculator works fine (not your phone or a graphing calculator). If you have questions about whether a calculator counts as "pocket," just ask.
- Read my [notes on questions](files/02-notes-questions.html) and
[notes on models](files/03-notes-models.html). Complete the exercises; you'll find some at the bottom of both sets of notes.
- Bookmark the course webpage for easy access. It's [https://pos3713ri.github.io](https://pos3713ri.github.io). I'll add material here throughout the semester.
- Make sure you have an up-to-date profile picture on Canvas. 
- Create an account on [Posit Cloud](https://posit.cloud). You can sign up directly or use an existing Google or GitHub account.

