---
title: "Week 1: Tools"
output:
  pdf_document: default
  html_document:
    toc: false
---

There are two versions of this file: an [html](01-hw-tools.html) and a [pdf](01-hw-tools.pdf). If you need to print the document, then the pdf works a little better.

If you find a problem with this assignment, then please start a discussion in our [Slack workspace](http://pos5737.slack.com), especially if the instructions don't work or you find them confusing. **This is important.** This assignment can be particularly frustrating, so if the instructions are unclear, inaccurate, or incomplete, let me know so that I can update them and save others some frustration.

In this homework assignment, you will some of software, create a couple of accounts, and make sure things work. You don't need to understand everything that's happening. That's expected and okay. You'll learn more about these tools later in the semester.

If you get an error following the steps below, *please* post to Slack so that I have a record of your difficultly, even if you figure it out relatively quickly. That helps me maintain high-quality materials that work for users with a range of abilities. While I work to make sure the instructions are accurate and correct, it's almost impossible to keep the instructions up-to-date. Help me out by point out inaccuracies. 

Definitely seek help before you get frustrated. This is not a course in installing software, so reach out well before it gets frustrating.

---

# At Some Point, Ask a Question

At some point in this assignment, find something that you don't completely understand. Start a discussion in our Slack workspace and ask your question. Also, respond to someone else's question. This should be an **actual question** (be aware of what you don't understand) and an actual response to someone else's question (share what you **do** understand).

---

# Slack

My graduate students have access to me over Slack, and you'll have the same access this semester. Slack is essentially a group messaging app, but it has a few other features that make it ideal for our class. It allows us to have a continuous group discussion throughout the week. 

Here are some great things about a group Slack channel, rather than e-mail:

1. It's faster. I process email once per day or so. I am on Slack during most working hours. 
1. It's easier for me to organize and manage.
1. If you have a question and I take the time to answer, others can learn from our exchange.
1. If someone asks a question, another student can respond, follow-up, and/or clarify.

Slack discussions have proven really valuable for my graduate classes during normal semesters, I expect it will work well for us during this digital semester.

Use the steps below to set up your Slack account.

**Choose an e-mail address that you'd like to associate with your Slack account.** I recommend using an e-mail account that you have control over (e.g., gmail), because you'll eventually lose your FSU e-mail account. (It seems that Slack does not allow you to associate multiple e-mail addresses with the same account.) Just e-mail me ([crainey@fsu.edu](mailto:crainey@fsu.edu) the address you prefer, and I'll invite you.

**Register a Slack account.** I'll send you an invitation to join our workspace. Accept the invite and fill out your profile, including (i) a profile picture and (ii) the "What I do" box.

**Familiarize yourself with Slack.** We use Slack as an alternative to e-mail and Canvas because (i) it's better and (ii) it's a tool you might encounter in industry. They have some [simple introductory videos](https://www.youtube.com/watch?v=EYqxQGmQkVw&list=PLWlXaxtQ7fUY6nF1dWTTBpe23rGv879_V) and an excellent [help center](https://get.slack.help/hc/en-us/categories/360000049043). 

**Consider getting the desktop and mobile apps.** They allow you to fine-tune notifications. For example, you can turn off notifications from 8pm to 8am. 

**Try out the #playground.** I created the #playground channel to experiment. Go there and try out a few features. Try something fun `(/giphy [emotion here])` and something more serious.

**Think about integrations.** If you are a productivity ninja that uses services like Evernote and Todoist, you can integrate those with Slack. 

---

# Reading

Read the following:

* [syllabus](syllabus.html)
* [syllabus](honesty.html)

---

# Show File Extensions on Your Computer

For reasons I don't understand, neither macOS nor Windows shows file extensions by default. (That's the `.docx` bit of the Word file `Essay for English 1101.docx`.)

**On Windows**, see the instructions [here](https://www.thewindowsclub.com/show-file-extensions-in-windows).

**On macOS**, open Finder. Click *Finder* > *Preferences...* Select *Advanced* tab and check the box to *Show all filename extensions*.

---

# R and RStudio

**Install (or Update) R.** Choose the appropriate OS from [CRAN](https://cloud.r-project.org/) and follow the instructions. On Windows, you get two versions of R: i386 and x64. This is normal. These are 32- and 64-bit versions We only use R indirectly through RStudio, so we never choose between the two. (But both work!)

**Install (or Update) RStudio.** You may choose either the [preview version](https://www.rstudio.com/products/rstudio/download/preview/) or the latest [stable version](https://www.rstudio.com/products/rstudio/download/#download). I use the preview version. The lab computers have the latest stable version. The preview version has new features; the latest stable version is (I suppose) more robust. Choose a version, select your OS, and follow the instructions.

*If you already had R installed*, **update your packages**. Just open RStudio and run `update.packages(ask = FALSE, checkBuilt = TRUE)`.

**Adjust One (Bad) Default.**  Click *Tools* > *Global Options...*. Select *General*. Under *Workspace*, set *Save workspace to .RData on exit:* to *Never*. Uncheck the box for *Restore .RData into workspace at startup.*

**Install the tidyverse package.** Open RStudio. In the lower-right pane, click the *Packages* tab to show the *Packages* window. You see a list of available packages. Click the *Install* button at the top of the *Packages* window, type "tidyverse" in the middle box, and click *Install*. Make sure that tidyverse installs successfully by entering the command `library(tidyverse)` in the console in the lower-left pane.

Comment: Other instructors might suggest the equivalent approach of entering the command `install.packages("tidyverse")` in the console, but I recommend the point-and-click method. It's easier and packages only need to be installed once per computer.

Comment: R packages allow software developers to distribute additional functionality to users. For example, you'll use the ggplot2 package to create graphs. [Hadley Wickham](http://hadley.nz) wrote ggplot2 as part of his dissertation in the statistics department at Iowa State. That was [version 0.0.7](https://github.com/tidyverse/ggplot2/tree/ggplot2-0.7) and we're now on [version 3.0.0](https://github.com/tidyverse/ggplot2/tree/v3.0.0). I'm excited for the next release because of [this annoying bug](https://github.com/tidyverse/ggplot2/issues/2787). 

Comment: When you run `library(tidyverse)`, you get the output below, which is both expected and desirable.

```{r}
library(tidyverse)
```

**Run an R script.** To start a new R script, open RStudio and click *File* > *New File* > *R Script*. This opens a blank R script in the upper-left pane. Copy-and-paste the code below into the R script. Use your mouse to highlight all eight lines (or press command + a) and then click *Run* (or press command + enter) at the upper-right of the script window. Make sure a scatterplot appears in the *Plot* tab of the lower-right pane. If so, you've got R and RStudio working.

```
# simple example script

# load packages
library(tidyverse)

# create two vectors of data
x <- c(2, 3, 5, 4, 1)  # x "gets" a "collection" of 5 numbers
y <- c(4, 2, 1, 5, 6)  # y "gets" a "collection" of 5 numbers

# plot x and y
qplot(x, y)
```

---

# LaTeX

## Install LaTeX

For **macOS**, I recommend [MacTeX](http://www.tug.org/mactex/). Download and follow the instructions. 

For **Windows**, I recommend [MiKTeX](https://miktex.org/download). Download and follow the instructions. Hopefully, the installer asks you if you would like MiKTeX to install missing packages on-the-fly. Choose *Yes* rather than *Ask Me*. (See [here](https://yihui.name/en/2018/03/miktex-auto-install/) for the details).

## Check LaTeX from RStudio

Open RStudio. Click *File* >  *New File* > *Text File*. Save as `latex-test.tex`. Create a new folder on the Desktop and save it there. Copy-and-paste the LaTeX code below into `latex-test.tex`. Click *Compile PDF*. Check that this creates the pdf you expect. Delete the pdf file.

```
% a minimal latex document
\documentclass{article}

\begin{document}
First document. If this compiles into a pdf, then LaTeX seems to work.
\end{document}
```

---

# R Markdown

Open RStudio. Click *File* > *New File* > *R Markdown*. Install any suggested packages. Fill in the *Title* and *Author* boxes however you like. Make sure the *HTML* bubble is selected (the default). This initiates an R Markdown document that serves as a helpful template. 

Notice that the R Markdown file contains a mix of R code and Markdown syntax. Don't sweat the details. (I make and maintain this website with R Markdown!)

Save the file as `rmarkdown-test.Rmd` to the Desktop.

Click the *Knit* button to knit the `.Rmd` into an `.html` file, which you can view with a web browser.

Check that you can also knit to a pdf document by clicking the tiny triangle next to the Knit button and then clicking *Knit to PDF*. (If you have MS Word, you might try that options as well.) 

When you are sure that R Markdown works for you, delete `rmarkdown-test.Rmd` from the Desktop and all the associated files that knitr generated.

---

# Finishing Up

Make sure you have completed the entire assignment (including asking and answering a question on Slack). Then complete the HW questionnaire, quiz, and letter on Canvas. These are due by Friday at 11:59pm. Please remind yourself of the standards of [academic honesty](honesty.html) as you complete the graded assignments.
