---
title: "Week 10: p-Values"
output:
  pdf_document: default
  html_document:
    toc: false
---

#### Hypothesis Tests and p-Values

This week, we end our discussion of sample surveys with $p$-values and hypothesis tests.

Here's where we've been (weeks 1-3) and where we are at (week 4):

- *week 1*: the box model, a tool that will be helpful for understanding sample surveys. We draw several times (with replacement) from this box and add up the numbers shown on the tickets. We want to fill in the following blanks: "The sum will be about ______, give or take _______ or so."
- *week 2*: "population," "sample," and other key terms. Given the population, what will the sample look like? "The sample percentage will be about the population percentage, give or take _______ or so."
- *week 3*: confidence intervals. These allow us to reverse the logic we've used before and reason from the sample back to the population.
- *week 4*: hypothesis tests, an alternative to confidence intervals for reasoning from sample to population.

Read **chs. 26, 27, and 29** of FPP and do the assigned review exercises [here](fpp-exercises.html). 

#### Finishing Up

Remember that both the TA and I have [office hours](https://canvas.fsu.edu/courses/133680/pages/zoom-office-hours) during the week. We're also available on Slack to chat. 

Make sure you have completed the entire assignment. Then complete the HW questionnaire, quiz, and letter on Canvas. These are due by Friday at 11:59pm. Please remind yourself of the standards of [academic honesty](honesty.html) as you complete the graded assignments.


