---
title: "Week 10: Correlation"
output:
  pdf_document: default
  html_document:
    toc: false
---


This week, we begin the last part of the class: a section on "regression."

I've decided to make one change. First, I'm going to push the due date for Computing Assignment 2 back to a TBD date. I'd like it to focus on regression. This will better prepare you for the research project.

#### Correlation

As a preliminary topic, we look first at the "correlation coefficient." **Read chs. 8 and 9 of FPP and do the assigned review exercises [here](fpp-exercises.html).**


#### Finishing Up

Remember that both the TA and I have [office hours](https://canvas.fsu.edu/courses/133680/pages/zoom-office-hours) during the week. We're also available on Slack to chat. 

Make sure you have completed the entire assignment. Then complete the HW questionnaire, quiz, and letter on Canvas. These are due by Friday at 11:59pm. Please remind yourself of the standards of [academic honesty](honesty.html) as you complete the graded assignments.


