---
title: "Week 1: Simple Regression"
output:
  pdf_document: default
  html_document:
    toc: false
---


This week, we continue working on regression. In particular, we extend the simple regression model to the **multiple** regression model. While the simple regression model uses a single explanatory variable $x$ to predict the outcome $y$, the multiple regression model uses *multiple* explanatory variables $x_1, x_2, ..., x_k$ to predict $y$.

Remember the two non-weekly assignments we have remaining this semester.

- Computing Assignment 2 is due Tuesday, Nov. 24 (by midnight). That will be your only assignment for this class for Thanksgiving week.
- The research project is due on Dec. 11 (by midnight), which is the last day of final exam week. I'll share more details about that after Thanksgiving, so you'll have two weeks to complete the assignment, which will give you a data set and ask you to do an open-ended data analysis and draw a conclusion.

There will be no quiz this week. Instead, you will upload a document with your answers to the assigned exercises below. For simplicity, it's still called "Quiz 13" in Canvas, but **Quiz 13 just asks you to upload a file with your answers to the exercises.** A PDF works best. You can either type your answers in Word or scan your handwritten answers using an app such as Scannable.

#### Multiple Regression

Write your solutions to the exercises below either neatly by hand or in Word. You'll upload a PDF of your answers instead of a Quiz this week. You can find Quiz 13 on Canvas, but it just asks you to upload your answers.

**Part 1**

Read ch. 2 of Wooldridge (2016). There's a link on the Canvas announcement for this week. (I plan to add a video discussion ch. 2 on Tuesday.)

Do Exercises 1-4 on pp. 53-54.

Do the following exercises as well:

1. Combining the mathematical notation with your own words, define the following terms: simple linear regression, dependent variable (which I call the "outcome variable"), independent variable (which I call the "explanatory variable"), error term, slope parameter, intercept parameter, PRF, fitted value, residual, OLS regression line, SRF, R-squared. SER, standard error of $\hat{\beta}_1$.
1. If the long-run average estimate of $\hat{\beta}_1$ equals the population value of $\beta_1$, then we say that the estimate $\hat{\beta}_1$ is "unbiased." Combining mathematical notation with your own words, describe the conditions under which the least-squares estimate $\hat{\beta}_1$ is unbiased. See Wooldridge (2016), section 2-5a, pp. 40-45. 

**Part 2**

Read ch. 3 of Wooldridge (2016). 

Do Exercises 1-2 on pp. 93.

Do the following exercises as well:

1. Combining the mathematical notation with your own words, define the following terms: certeris paribus interpretation,perfect collinearity, exogenous and endogenous explanatory variable, omitted variable bias, Gauss-Markov assumptions, multicollinearity (contract with perfect collinearity), Gauss-Markov Theorem.
1. Combining mathematical notation with your own words, describe the conditions under which the least-squares estimate $\hat{\beta}_j$ is unbiased for $j \in {0, 1, 2, ... k}$. See Wooldridge (2016), section 3-3, pp. 73-77, esp Theorem 3.1. 

#### Computing Assignment 2

Complete [Computing Assigment 2](ca/ca2.html). It's due Tuesday, Nov. 24, by midnight. As I respond to student questions, I occasionally update the assignment. If you see things that I can clarify, please let me know. 

#### Finishing Up

Remember that both the TA and I have [office hours](https://canvas.fsu.edu/courses/133680/pages/zoom-office-hours) during the week. We're also available on Slack to chat. 

Make sure you have completed the entire assignment. Then complete the HW questionnaire, quiz (a file upload, see above), and letter on Canvas. These are due by Friday at 11:59pm. Please remind yourself of the standards of [academic honesty](honesty.html) as you complete the graded assignments.

**Thanksgiving week extensions.** Thanksgiving can be a difficult time. Some of us will be away from our families, and that will be hard. Others might be with our families and that might be hard, for different reasons. I expect that you'll have lots of assignments due this week. While the usual assignments are due on Friday and the Computing Assignment is due on Tuesday, I'll be generous with extensions if you need them. I'll give anyone who asks until Sunday, Nov. 29. That said, if you can, I strongly encourage you to finish this assignment on time (or early) and enjoy the break.



