---
title: "Week 14: Regression Extensions"
output:
  pdf_document: default
  html_document:
    toc: false
---


In our last week, we continue working on regression, tackling a grab-bag of miscellaneous extensions. We're also starting the research project. 

#### Regression Extensions

We're going to extend the multiple regression model in three ways.

1. Dummy variables
1. Interactions 
1. Logistic regression

There's no readings. I'll post a video here soon. The quiz will be relatively easy. You should just watch the video, take a good notes, and the quiz should be straightforward.

#### Research Project

Complete [the research project](ca/rp.pdf). It's due Friday, Dec. 11, by midnight. As I respond to student questions, I occasionally update the assignment. If you see things that I can clarify, please let me know. 

#### Finishing Up

Remember that both the TA and I have [office hours](https://canvas.fsu.edu/courses/133680/pages/zoom-office-hours) during the week. We're also available on Slack to chat. 

Make sure you have completed the entire assignment. Then complete the HW questionnaire, quiz and letter on Canvas. These are due by Friday at 11:59pm. Please remind yourself of the standards of [academic honesty](honesty.html) as you complete the graded assignments.



