---
title: "Assignment 17"
---

## Research Paper

The 1st draft of the research paper is due Thursday. For this draft, prioritize completeness over polish. It's better to have all the sections present (even if rough) rather than have a polished introduction without any data. At this point, you should clearly make a descriptive claim, explain the claim's importance, and use data to demonstrate the correctness of the claim.

Here is a minimal set of sections that you might use:

1. **Introduction**. Booth's "[context, problem, solution](https://www.dropbox.com/scl/fi/f5r0gu6vit8sszabbreai/99-booth-ch16.pdf?rlkey=hbiktza7zfd8sg25ykna1qm7r&dl=0)" formula is very helpful advice. For example: 
   a. *Context*: There's an explosion of research on affective polarization.
   a. *Problem*: But we don't know whether these pernicious trends are consistent across racial groups. (Be sure to explain why this is an *important* problem--0why should we care if trends among racial groups are similar or different?)
   a. *Solution*: We use the ANES to show...
1. **Data and Measures**. Explain your data and measures clearly and carefully.
1. **Results** (included tables and figures). Explain your procedures and results carefully.
1. **Conclusion**. See Booth above.

## Lecture and Notes

In class, I used [these slides](files/31-basics-of-probability.pdf). 

Before next class, read [these notes](https://pos3713ri.github.io/inference-notes/the-basics-of-probability.html) (ch. 2 only) and do the exercises throughout.