---
title: "Assignment 19"
---

::: callout-note

## Poster

We'll have the poster session on **December 4** from 9:45 to 11 on the 5th floor of Bellamy.

- You'll need to have your posters turned in to me by Tuesday, **November 25** for printing.
- Your poster must be 36" (W) by 24" (H).
- Requirements and tips for the posters are [here](https://gist.github.com/carlislerainey/cfd128077ba7bff3350022129bb097c2). 

:::

::: callout-tip

## Extra Credit Opportunity!

You will receive **three points of extra credit on Exam 2** for each workshop you attend. 

✅ **Sign up [here](https://docs.google.com/forms/d/e/1FAIpQLSfJ3NRAD-bCD6R1UNYJwwxKm6eSRivlLN2usS8F1hbAmIcMag/viewform?usp=preview).**

---


My PhD students are working hard this semester to learn and teach advanced statistical modeling. As part of their course, they are putting on three 60-minute workshops. 

- *Modeling Unordered Categorical Outcomes*. Tuesday, November 18 from 1pm to 2pm.
- *Modeling Ordered Categorical Outcomes*. Wednesday, November 19 from 1pm to 2pm.
- *Modeling Time-to-Event Outcomes*. Friday, November 21 from 11am to 12noon.

:::

## Lecture and Notes

In class, I used [these slides](files/33-sample-survey.pdf). 

Before next class, read [these notes](https://pos3713ri.github.io/inference-notes/sample-surveys.html) and do the exercises throughout.