project:
  type: website
  output-dir: docs
  resources:
    - syllabus.pdf
    - exr/
    - files/
    - data/
  execute-dir: project  
    
  render:
    - "*.qmd"
    - "!drafts/*.qmd"
    - "!scratchpad.qmd"


website:
  title: "POS 3713"
  site-url: https://pos3713ri.github.io/
  google-analytics: "G-F57WQLHH67"
  navbar:
    left:
      - text: "Schedule"
        href: index.qmd
      - text: "Research Project"  
        href: research-project.qmd
      - text: "Syllabus"
        href: syllabus.pdf
      - text: "Data"
        href: data.qmd
        
format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true        
