---
title: "Data"
output:
  html_document
---

## Clean, Tidy Data Sets

The data sets below are ready to visualize and model. They are [tidy](https://vita.had.co.nz/papers/tidy-data.pdf). I filtered out useful subsets. I selected and descriptively renamed the most important variables. I meaningfully reordered factors.

| Name                	| Data Files                           	| Codebook 	| Description                                         	|
|---------------------	|--------------------------------------	|----------	|-----------------------------------------------------	|
| `gamson`| [[`.csv`](data/gamson.csv)] [[`.dta`](data/gamson.dta)] [[`.rds`](data/gamson.rds)] [[`.xlsx`](data/gamson.xlsx)] 	| [[html](data/gamson-codebook.html)]| From Warwick and Druckman (2006)      | 
| `health`            | [[`.csv`](data/health.csv)] [[`.dta`](data/health.dta)] [[`.rds`](data/health.rds)] [[`.xlsx`](data/health.xlsx)] 	| [[html](data/health-codebook.html)]| From Barrilleaux and Rainey (2014).                 	|
| `nominate`| [[`.csv`](data/nominate.csv)] [[`.dta`](data/nominate.dta)] [[`.rds`](data/nominate.rds)] [[`.xlsx`](data/nominate.xlsx)] 	| [[html](data/nominate-codebook.html)]| Ideology scores for members of the U.S. House.                  	|
| `parties`          	| [[`.csv`](data/parties.csv)] [[`.dta`](data/parties.dta)] [[`.rds`](data/parties.rds)] [[`.xlsx`](data/parties.xlsx)] 	| [[html](data/parties-codebook.html)]   	| From Clark and Golder (2006)     .             	|
| `state-legislators`          	| [[`.csv`](data/state-legislators.csv)] [[`.dta`](data/state-legislators.dta)] [[`.rds`](data/state-legislators.rds)] [[`.xlsx`](data/state-legislators.xlsx)] 	|    	|           	|

## Original Data Sources

* For **replication data sets**, I recommend starting with the Dataverse archives for *AJPS* [[web](https://dataverse.harvard.edu/dataverse/ajps) and *PSRM*.
* For __*really* raw data__ for wrangling practice, I recommend (ordered from least to most difficult) Donald Trump's tweets [[GitHub](https://github.com/pos5737/tweets)], the World Bank's World Development Indicators [[GitHub](https://github.com/pos5737/wdi)], Google political ads data  [[web](https://transparencyreport.google.com/political-ads/library), [Dropbox](https://www.dropbox.com/sh/mp1w295gg0os5qg/AAAfVGjoYe6dEB7-nn0ucpWaa?dl=0)], or 10 million dyadic events [[Dataverse](https://dataverse.harvard.edu/dataset.xhtml?persistentId=hdl:1902.1/FYXLAWZRIA)].
* For data on **international politics**, I recommend COW [[web](http://www.correlatesofwar.org/data-sets)], DESTA [[web](https://www.designoftradeagreements.org/downloads/)], and Matt Fuhrmann's data on nuclear weapons [[web](http://www.matthewfuhrmann.com/datasets.html)].
* For data on **political institutions**, I recommend Polity IV [[web](http://www.systemicpeace.org/inscrdata.html)], DD [[web](https://sites.google.com/site/joseantoniocheibub/datasets/democracy-and-dictatorship-revisited)], Freedom House [[web](https://freedomhouse.org/report-types/freedom-world)], and DES [[web](http://mattgolder.com/elections)].
* For **US state politics**, I recommend the Correlates of State Policy data set [[web](http://ippsr.msu.edu/public-policy/correlates-state-policy)], which combines variables from many projects in single, enormous collection.
* For data on **legislator ideology**, I recommend NOMINATE [[web](https://voteview.com/data)] and the American Legislatures Project [[web](https://americanlegislatures.com/data/)].
* For data on **human rights**, I recommend Human Rights Scores [[web](http://humanrightsscores.org)], PTS [[web](http://www.politicalterrorscale.org/Data/)], CIRI [[web](http://www.humanrightsdata.com/p/data-documentation.html)], and ITT [[web](http://faculty.ucmerced.edu/cconrad2/Academic/ITT_Data_Collection.html)].
* For **survey data**, I recommend the ANES [[web](https://electionstudies.org/data-center/)], CCES [[web](https://cces.gov.harvard.edu)], CSES [[web](http://www.cses.org/verify.htm)], and the World Values Survey [[web](http://www.worldvaluessurvey.org/WVSContents.jsp)].
* For data from **randomized experiments**, I recommend TESS [[web](http://www.tessexperiments.org/previousstudies.html)].
* Google now has a [search for data sets](https://toolbox.google.com/datasetsearch).
* Let's go meta: [PolData](https://github.com/erikgahner/PolData) is a data set of data sets.
