---
title: "Assigned Exercises from Freedman, Pisani, and Purves"
output: pdf_document
---

Below are the assigned exercises for the assigned chapters of Freedman, Pisani, and Purves. 

Exercises Sets (e.g., Exercise Set A on p. 20) follow each short section of book. You should complete the assigned exercises from each Set immediately after reading that section. We will not usually discuss these exercises in class (unless you have specific questions), but the answers are given in the back of the book. The assigned exercises are simply my suggestions to test your knowledge of the material in the preceeding section. If you find these problems difficult, you should try a few more from that set.

Review Exercises (e.g., Section 6, p. 24) follow most chapters in the book. You should complete the assigned Review Exercises immediately after reading the chapter. Think about these problems carefully, because we will usually discuss these problems in class.

Chapters 1 and 2

- Set A, p. 20: 1-3, 8. 
- Section 6, p. 24: 4, 7, 11, 12. 

Chapter 3

- Set A, p. 33: 3, 4. 
- Set B, p. 38: 1-3. 
- Set C, p. 41: 4. 
- Set D, p. 44: 1. 
- Set E, p. 46: 1. 
- Set F, p. 47: 1.
- Section 8, p. 50: 2, 4, 7, 9, 12

Chapter 4

- Set A, p. 60: 1-4, 8. 
- Set B, p. 65: 1, 2, 5. 
- Set C, p. 67: 1, 2. 
- Set D, p. 70: 1, 2, 4, 6. 
- Set E, p. 72: 4-8.
- Section 8, p. 74: 1-6, 9, 12

Chapter 5

- Set A, p. 82: 1, 2. 
- Set B, p. 84: 1-5. 
- Set C, p. 88: 1-2. 
- Set D, p. 89: 1-2. 
- Set E, p. 92: 1-3. 
- Set F, p. 93: 1.
- Section 7, p. 93: 1-4, 8.

Chapter 6

- Section 5, p. 104: 1-5.

Chapter 7

- Set E, p. 116: 1.

Chapter 8

- Set A, p. 122: 1, 2, 6.
- Set B, p. 128: 1-3, 6.
- Set C, p. 131: 1-4.
- Set D, p. 134: 1a, 2-4.
- Section 5, p. 134: 1-3, 5, 7, 8(a-c), 9a, 9b, 10.

Chapter 9

- Set A, p. 143: 2-6, 9.
- Set B, p. 145: 1.
- Set C, p. 148: 1, 3, 4.
- Set D, p. 150: 2.
- Set E, p. 152: 3-5.
- Section 6, p. 153: 1, 2, 4, 5-8, 10, 12.

Chapter 10

- Set A, p. 161: 1-4.
- Set B, p. 163: 1, 3.
- Set C, p. 167: 1-3.
- Set D, p. 174: 1, 2.
- Set E, p. 175: 1, 2.
- Section 6, p. 176: 1-3, 5-7, 10.

Chapter 11

- Set A, p. 184: 1-4, 6, 7.
- Set B, p. 187: 1, 2.
- Set C, p. 189: 1-3.
- Set D, p. 193: 1, 2, 4-6.
- Set E, p. 197: 1, 2.
- Section 6, p. 198: 1, 2, 4, 6, 7,10, 12.

Chapter 12

- Set A, p. 207: 1, 2, 3, 4.
- Set B, p. 210: 1, 2.
- Section 4, p. 213: 1-5, 8.

Chapter 13

- Set A, pp. 225-226: 1-3, 5.
- Set B, p. 227: 1-4. Pay special attention to "Technical Notes" at the end of the section.
- Set C, pp. 229-230: 1-3, 7. You need to memorize the multiplication rule. Also, pay special attention to the differences between (a) and (b) in questions 1-3.
- Set D, p. 232: 1-7. Note that independence is a critical concept to everything we do for the rest of the semester. Make sure you understand it.

Chapter 14

- Set A, pp. 240-241: 1-3.
- Set B, pp. 242-243: 2, 4, 5.
- Set C, pp. 246-247: 1-3, 5.
- Set D, pp. 250-251: 1-, 4.
- Review Exercises, pp. 252-254: 1-3, 5-7, 11.

Chapter 16

- Set A, pp. 277-278: 1-4, 6-8.
- Set B, pp. 280-281: 1-3, 6.
- Set C, pp. 284-285: 1-3.
- Review Exercises, pp. 285-286: 1, 2, 4, 7, 8, 10.
    
Chapter 17

- Set A, p. 290: 1, 2.
- Set B, pp. 293-294: 1-5.
- Set C, pp. 296-297: 1-4.
- Set D, p. 299: 1.
- Set E, pp. 303-304: 1-3.
- Review Exercises, pp. 304-306: 1, 3-8, 11, 12. 
    
Chapter 18 

- Set A, pp. 312-315: 1, 2, 4, 5.
- Set B, pp. 318-319: 1-3.
- Set C, pp. 324-325: 1-5, 8.
- Review Exercises, pp. 327-329: 1-6, 8-10, 15.
    
Chapter 19

- Set A, pp. 349-351: 1-6, 8, 11, 12
- Review Exercises, pp. 351-353: 1, 4, 6, 9, 12.
    
Chapter 20 

- Set A, pp. 361-362: 1-4, 8.
- Set B, p. 366: 1, 2, 4.
- Set C, p. 370: 1, 4, 5.
- Review Exercises, pp. 371-373: 1-3, 6, 7, 11.    
  
Chapter 21

- Set A, pp. 379-380: 1-3, 7, 8.
- Set B, p. 383: 2, 4.
- Set C, pp. 386-387: 1-4, 6, 7.
- Set D, pp. 388-389: 1, 2.
- Set E, pp. 390-391: 1-3.
- Review Exercises, pp. 391-394: 1, 2, 7, 8, 13, 15.  
    
Chapter 23

- Set A, pp. 413-414: 1, 2, 4, 9.
- Set B, pp. 420-421: 1, 2, 4-6.
- Set C, pp. 423-424: 1, 2, 4.
- Set D, pp. 424-425: 1-3, 5, 6.
- Review Exercises, pp. 425-428: 1, 6, 7, 10, 12.    
    
Chapter 26 (up to Section 6 titled "The *t*-Test", pp. 475-488)

- Set A, pp. 476-477: 5.
- Set B, p. 478: 1-5.
- Set C, pp. 481-482: 1-5.
- Set D, pp. 482-483: 1-3, 5.

Chapter 27

- Set A, p. 503: 1, 2.
- Set B, pp. 506-508: 1-4.
- Set C, pp. 511-512: 1-4.
- Set D, pp. 514-516: 1-2, 6.
- Review Exercises, pp. 518-521: 1, 3, 7.
- Set E, pp. 486-488: 1-5, 7.    