---
title: "Schedule"
---

Note: Complete the homework *after* the associated class, but *before* the next class.


**Aug 26**: Questions and Models [[hw](01-hw.html)]

**Aug 28**: R [[hw](02-hw.html)] [[notes](files/02-notes-computing.html)]

**Sep 2**: Data [[hw](03-hw.html)] [[slides](files/03-slides-dfs.pdf)] [[notes](files/03-notes-dfs.html)]

**Sep 4**: Causality and Histograms [[hw](04-hw.html)] [[slides](files/04-slides-causality.pdf)]

**Sep 9**: Histograms in R [[hw](05-hw.html)] [[notes](files/05-notes-histograms-R.qmd)] [[Computing Assignment 1](files/ca1.qmd)]

**Sep 11**: Avg and SD [[hw](06-hw.qmd)]

**Sep 16**: Avg and SD in R [[hw](07-hw.qmd)] [[notes](files/07-notes-avg-sd-R.qmd)]

**Sep 18**: Normal Model [[hw](08-hw.qmd)] [[slides](files/08-normal-approx.pdf)]

**Sep 23**: Review  
[[Computing Assignment 1](files/ca1.qmd) due.]{.remarks}

**Sep 25**: [**Exam 1**]{.text-warning}  

**Sep 30**: Wrangling 1 [[hw](09-hw.qmd)]

**Oct 2**: Wrangling 2 [[hw](10-hw.qmd)]

**Oct 7**: Scatterplots [[hw](11-hw.qmd)]  

**Oct 9**: Correlation [[hw](12-hw.qmd)] 

**Oct 14**: Regression [[hw](13-hw.qmd)] [[slides](files/sl-regression/sl-regression.html)]

**Oct 16**: Regression in R [[hw](14-hw.qmd)]

**Oct 21**: Multiple Regression [[hw](15-hw.qmd)]
[RP prospectus due.]{.remarks}

**Oct 23**: Extensions to Multiple Regression [[hw](16-hw.qmd)]  

**Oct 28**: Review  

**Oct 30**: [**Exam 2**]{.text-warning}

**Nov 4**: Probability Basics  

**Nov 6**: Numbered-Ticket Model  
[RP 1st draft due.]{.remarks}

**Nov 11**: [Veterans Day - No Classes]{.text-success}

**Nov 13**: Sample Surveys  
[RP peer review due.]{.remarks}

**Nov 18**: Randomized Experiments  

**Nov 20**: Confidence Intervals  

**Nov 25**: Hypothesis Tests  

**Nov 27**: [Thanksgiving - No Classes]{.text-success} 

**Dec 2**: Wrap  
[RP poster presentation around here.]{.remarks}

**Dec 4**: Review  
[Computing Assignment 2 due.]{.remarks}

**Dec 9**: [**Final Exam**]{.text-warning}, 7:30 a.m.– 9:30 a.m.  
[RP final draft due.]{.remarks}
