---
title: "Computing Assignment 2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Do the following:

1. Start a new project in RStudio. 
1. Get the [`.csv version`](https://raw.githubusercontent.com/pos5737/economic-models/master/data/economic-models.csv) of the economic models data set from GitHub. Save it to the `data/` subdirectory of your project as `economic-models.csv`. You can find out more about the data set and the variables in the [README](https://github.com/pos5737/economic-models/blob/master/README.md#the-dataset) on GitHub. The data set contains three variables that we might use to predict the incumbent margin of victory in presidential elections: % change in RDI, % change in GDP, and unemployment rate.
1. Start a new R script. Save the script as `analysis.R`.
1. In the script, do the following (include comments!):
   a. Load the tidyverse package.
   a. Load the data file `economic-models.csv`.
   a. Use the glimpse functions to quickly (1) check the data are what you expect and (2) see the variable names.
   a. Create three scatterplots, one for each predictor (% change in GNI, % change in GDP, and unemployment rate). In each scatterplot, put the incumbent margin of victory along the y-axis and the predictor along the x-axis. Add a regression line.
   a. In a comment, assess how well you think each of the three predictors explains the variation in the incumbent margin of victory.
   a. For each of the three predictors, fit a simple regression model using `lm()`. 
   a. In a comment, interpret the slope. "A one [unit] increase in [the predictor] leads to a ____ percentage point [increase/decrease] in the incumbent's margin of victory." 
   a. In anther comment, use the simple regressions to assess how well you think each of the three predictors explains the variation in the incumbent margin of victory. Hint: `arm::display()` gives you both the RMS of the residuals (`residual sd`) and the R-squared.
   a. Now fit a single model that includes all three predictors. You can easily do this with the syntax `lm(y ~ x1 + x2 + x3, ...)` (rather than just `lm(y ~ x, ...)`). 
   a. In a comment, interpret the slopes from the multiple regression model. "Holding [the other two predictors] constant, a one [unit] increase in [this predictor] leads to a ____ percentage point [increase/decrease] in the incumbent's margin of victory." 
   a. In another comment, explain how well this multiple regression model explains the variation in the incumbent margin of victory compared to each of the three simple regression models. Hint: `arm::display()` gives you both the RMS of the residuals and the R-squared for multiple regression models, too.
   
Once you are satisfied with your code and observations, click the tiny notebook icon (to the left of the *Run* button). When prompted, select *PDF* (PDF tends to work better, in my experience) or *MS Word*. Submit the `.pdf` or `.docx` file via Canvas.

# Avoid a Potential Bug

William F. kindly pointed out a potential problem that I did not anticipate. If you save the R script to a subdirectory of the project directory, then the steps above will fail when you try to create the PDF. 

Here's how to solve: 

- In RStudio, go to *Tools* > *Global Options...*. 
- Then select the *R Markdown* menu. Then change the dropdown menu for *Evaluate chunks in directory:* from Document to *Project*.

These steps ensure that the paths are relative to the project directory, not the directory where the R script is saved.

# Examples

The following shows the basic format of the R code and shows what the output should look like after you compile it into a notebook. The plots will look different, these simply show the formatting.

- R script [[R](../ca/example.R)]
- MS Word Output [[docx](../ca/example.docx)]
- PDF Output [[pdf](../ca/example.pdf)]