---
title: "Assignment for Class 1"
---

### Homework

Please complete before the next class.

- Read the [syllabus](syllabus.pdf) carefully. If I've missed anything or failed to clearly explain any policy, please let me know. Come prepared to the next class with any questions or comments.
- Order the [simple pocket calculator](https://www.amazon.com/gp/aw/d/B003822IRA/) that you'll need for homework and exams, or make a plan to buy one (e.g., Walmart or other stores). Any "pocket" calculator works fine (not your phone or a graphing calculator). If you have questions about whether a calculator counts as "pocket," just ask.
- Review my slides, your notes from class, and my notes.
- Complete the exercises in my notes. You'll find some at the bottom of both sets.
- Bookmark the course webpage for easy access. It's [https://pos3713ri.github.io](https://pos3713ri.github.io). I'll add material here throughout the semester.
- Make sure you have an up-to-date profile picture on Canvas. 
- Create an account on [Posit Cloud](https://posit.cloud). You can sign up directly or use an existing Google or GitHub account.

